apiVersion: v1
kind: Service
metadata:
  name: guestbook-http
spec:
  clusterIP: 10.106.0.6
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  selector:
    app: guestbook
